### ISSUE TITLE
stateError:null with Internet Explorer8

### ISSUE THREAD

**Issue by Neidell** [bem/gemini#101] opened 2015-01-15 13:17 UTC
Hi! I'm trying to run tests on my virtual machine with WinXP and IE8. When test is running i can see that IE opening required page and all looks good but the test fails with "stateError: null".

**Comment by SevInf** [comment] 2015-01-25 10:36
Hi.
Sorry for the late response. IE8 is not supported for now. We are currently working on it in the branch `feature/ie8`.
Closing this as a duplicate of #82

**Closed by SevInf** 2015-01-25 10:36 UTC
